<a href="https://colab.research.google.com/github/feliperodighero/Machine-Learning-Study/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('mt_cars.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  32 non-null     object 
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64  
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64  
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64  
 9   am          32 non-null     int64  
 10  gear        32 non-null     int64  
 11  carb        32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [5]:
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [6]:
X = df[['mpg', 'hp']].values
y = df['cyl'].values

In [7]:
knn = KNeighborsClassifier(n_neighbors=3)
model = knn.fit(X, y)

In [8]:
model

KNeighborsClassifier(n_neighbors=3)

In [9]:
y_pred = model.predict(X)

In [10]:
print(y_pred)

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]


In [13]:
accuracy = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred, average='weighted')
recall = recall_score(y, y_pred, average='weighted')
f1 = f1_score(y, y_pred, average='weighted')
cm = confusion_matrix(y, y_pred)

In [14]:
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Accuracy: 0.9375
Precision: 0.9395833333333333
Recall: 0.9375
F1 Score: 0.9372947454844006


In [15]:
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]


In [16]:
new_data = np.array([[19.3, 105]])

In [17]:
prediction = model.predict(new_data)

In [18]:
print(f"Prediction for new data: {prediction}")

Prediction for new data: [6]


In [20]:
distance, indices = model.kneighbors(new_data)

print("Indices of nearest neighbors:")
print(indices)

print("\nDistances to nearest neighbors:")
print(distance)

Indices of nearest neighbors:
[[ 5 31  1]]

Distances to nearest neighbors:
[[1.2        4.5177428  5.28109837]]


In [24]:
df.loc[indices[0], ['cyl', 'mpg', 'hp']]

cyl   mpg   hp
5     6  18.1  105
31    4  21.4  109
1     6  21.0  110